services:
  postgres:
    image: postgres
    container_name: carsties.postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  mongo:
    image: mongo
    container_name: carsties.mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: carsties.rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  identity-svc:
    image: hernancote/identity-svc:latest
    container_name: carsties.identity-svc
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__CarstiesConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
    ports:
      - 5001:80
    depends_on:
      - postgres
  auction-svc:
    image: hernancote/auction-svc:latest
    container_name: carsties.auction-svc
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__CarstiesConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=auctions
      - AuthenticationSettings__IdentityServiceUrl=http://identity-svc
    ports:
      - 7001:80
    depends_on:
      - postgres
      - rabbitmq
  search-svc:
    image: hernancote/search-svc:latest
    container_name: carsties.search-svc
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - AuctionServiceSettings__BaseUrl=http://auction-svc
      - MongoDbSettings__ConnectionString=mongodb://root:mongopw@mongo
    ports:
      - 7002:80
    depends_on:
      - mongo
      - rabbitmq
  gateway-svc:
    image: hernancote/gateway-svc:latest
    container_name: carsties.gateway-svc
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
